 INSERT INTO shoes (Sname, image, details, size, color)
VALUES 
  ('Reebok Nano X', 'https://example.com/reebok_nano_x.jpg', 'Versatile training shoes with support and durability', 9, 6),
  ('Vans Slip-On', 'https://example.com/vans_slip_on.jpg', 'Easy-to-wear slip-on sneakers for casual style', 8, 4),
  ('Under Armour HOVR Phantom', 'https://example.com/ua_hovr_phantom.jpg', 'Smart running shoes with connected technology', 11, 7),
  ('Brooks Adrenaline GTS', 'https://example.com/brooks_adrenaline_gts.jpg', 'Stability running shoes for a smooth ride', 10, 12),
  ('Adidas Superstar', 'https://example.com/adidas_superstar.jpg', 'Classic Adidas sneakers with a shell toe', 7, 19),
  ('Salomon Speedcross', 'https://example.com/salomon_speedcross.jpg', 'Trail running shoes for off-road adventures', 12, 15),
  ('Fila Disruptor II', 'https://example.com/fila_disruptor_ii.jpg', 'Chunky sneakers for a trendy and bold look', 8, 23),
  ('Mizuno Wave Rider', 'https://example.com/mizuno_wave_rider.jpg', 'Neutral running shoes known for comfort', 11, 2),
  ('Merrell Moab 2', 'https://example.com/merrell_moab_2.jpg', 'Hiking shoes with Vibram traction for outdoor enthusiasts', 14, 13),
  ('ASICS Gel-Nimbus', 'https://example.com/asics_gel_nimbus.jpg', 'High-performance running shoes with gel cushioning', 9, 21),
 ('Nike Air Max', 'https://example.com/nike_air_max.jpg', 'Comfortable and stylish Nike sneakers', 10, 5),
  ('Adidas Ultraboost', 'https://example.com/ultraboost.jpg', 'Adidas running shoes with Boost technology', 8, 12),
  ('Converse Chuck Taylor', 'https://example.com/chuck_taylor.jpg', 'Classic Converse sneakers for everyday wear', 7, 3),
  ('Vans Old Skool', 'https://example.com/old_skool.jpg', 'Iconic Vans skate shoes with a classic look', 9, 8),
  ('Puma RS-X', 'https://example.com/puma_rs_x.jpg', 'Pumas retro-inspired sneakers with a modern twist', 11, 15),
  ('Nike React Element 55', 'https://example.com/react_element_55.jpg', 'Modern Nike sneakers with React foam cushioning', 11, 16),
  ('Brooks Ghost 13', 'https://example.com/brooks_ghost_13.jpg', 'Neutral running shoes with plush cushioning', 10, 7),
  ('Adidas NMD R1', 'https://example.com/adidas_nmd_r1.jpg', 'Stylish Adidas sneakers with a sock-like fit', 9, 22),
  ('New Balance Fresh Foam 1080v11', 'https://example.com/nb_fresh_foam_1080v11.jpg', 'Premium cushioned running shoes for long distances', 12, 4),
  ('Under Armour Curry 8', 'https://example.com/ua_curry_8.jpg', 'Basketball shoes designed for Stephen Curry', 13, 14),
  ('Converse Chuck 70', 'https://example.com/chuck_70.jpg', 'Classic Converse sneakers with upgraded features', 8, 18),
  ('Salomon XA Pro 3D', 'https://example.com/salomon_xa_pro_3d.jpg', 'Durable trail running shoes with advanced stability', 11, 9),
  ('Puma Cali', 'https://example.com/puma_cali.jpg', 'Casual Puma sneakers inspired by West Coast style', 7, 11),
  ('Reebok Zig Kinetica', 'https://example.com/reebok_zig_kinetica.jpg', 'Energetic Reebok sneakers with a futuristic design', 10, 20),
  ('ASICS GT-2000', 'https://example.com/asics_gt_2000.jpg', 'Stability running shoes with a comfortable fit', 9, 2);
   ('Fila Ray Tracer', 'https://example.com/fila_ray_tracer.jpg', 'Retro-inspired Fila sneakers with a chunky sole', 8, 24),
  ('Vivobarefoot Primus Lite', 'https://example.com/vivobarefoot_primus_lite.jpg', 'Minimalist running shoes for natural movement', 11, 1),
  ('Mizuno Wave Inspire', 'https://example.com/mizuno_wave_inspire.jpg', 'Supportive Mizuno running shoes for overpronation', 10, 15),
  ('Saucony Kinvara 12', 'https://example.com/saucony_kinvara_12.jpg', 'Lightweight and responsive running shoes', 9, 19),
  ('Lowa Renegade GTX', 'https://example.com/lowa_renegade_gtx.jpg', 'Waterproof hiking boots for outdoor adventures', 13, 8),
  ('Hoka One One Bondi 7', 'https://example.com/hoka_bondi_7.jpg', 'Maximalist running shoes with excellent cushioning', 12, 11),
  ('Converse Chuck 70 High', 'https://example.com/chuck_70_high.jpg', 'High-top version of the classic Chuck 70 sneakers', 7, 5),
  ('Timberland 6-Inch Premium', 'https://example.com/timberland_6_inch_premium.jpg', 'Classic Timberland boots for urban and outdoor use', 11, 14),
  ('Adidas Stan Smith', 'https://example.com/adidas_stan_smith.jpg', 'Iconic Adidas tennis shoes with a clean design', 8, 21),
  ('Under Armour Charged Assert 8', 'https://example.com/ua_charged_assert_8.jpg', 'Versatile running shoes with UA Charged cushioning', 10, 3),
  ('Skechers DLites', 'https://example.com/skechers_dlites.jpg', 'Fashionable Skechers sneakers with air-cooled memory foam', 9, 23),
  ('On Cloud', 'https://example.com/on_cloud.jpg', 'Lightweight On running shoes for a cushioned ride', 10, 7),
  ('Asics Tiger Gel-Lyte III', 'https://example.com/asics_tiger_gel_lyte_iii.jpg', 'Classic Asics sneakers with a split tongue design', 8, 18),
  ('Merrell Jungle Moc', 'https://example.com/merrell_jungle_moc.jpg', 'Casual slip-on shoes with Merrell comfort technology', 7, 13),
  ('Hoka One One Clifton 8', 'https://example.com/hoka_clifton_8.jpg', 'Maximalist running shoes with a smooth ride', 11, 2),
  ('Vibram FiveFingers', 'https://example.com/vibram_fivefingers.jpg', 'Toe shoes for a barefoot-like running experience', 12, 10),
  ('New Balance 574', 'https://example.com/nb_574.jpg', 'Classic New Balance sneakers with timeless style', 8, 15),
  ('Fila Disruptor III', 'https://example.com/fila_disruptor_iii.jpg', 'Updated version of the chunky Fila Disruptor sneakers', 9, 20),
  ('Under Armour HOVR Sonic 4', 'https://example.com/ua_hovr_sonic_4.jpg', 'Connected running shoes with UA HOVR technology', 10, 5),
  ('Brooks Launch 8', 'https://example.com/brooks_launch_8.jpg', 'Neutral running shoes with energy return technology', 11, 14),
   ('Nike Blazer Mid', 'https://example.com/nike_blazer_mid.jpg', 'Classic Nike basketball-inspired sneakers with a retro touch', 8, 23),
  ('Adidas Gazelle', 'https://example.com/adidas_gazelle.jpg', 'Timeless Adidas sneakers with a suede upper', 7, 12),
  ('Puma Future Rider', 'https://example.com/puma_future_rider.jpg', 'Urban-inspired Puma sneakers with a comfortable fit', 9, 15),
  ('Saucony Jazz Original', 'https://example.com/saucony_jazz_original.jpg', 'Vintage Saucony sneakers known for their comfort', 10, 18),
  ('Reebok Club C 85', 'https://example.com/reebok_club_c_85.jpg', 'Classic Reebok tennis shoes with a clean design', 8, 10),
  ('Converse One Star', 'https://example.com/converse_one_star.jpg', 'Iconic Converse sneakers with a distinctive star logo', 7, 5),
  ('New Balance 990v5', 'https://example.com/nb_990v5.jpg', 'Premium New Balance running shoes with superior cushioning', 12, 20),
  ('Vans Sk8-Hi', 'https://example.com/vans_sk8_hi.jpg', 'High-top Vans sneakers for a skate-inspired look', 9, 14),
  ('Under Armour Charged Pursuit 2', 'https://example.com/ua_charged_pursuit_2.jpg', 'Versatile running shoes with UA Charged cushioning', 10, 7),
  ('Brooks Glycerin 19', 'https://example.com/brooks_glycerin_19.jpg', 'Cushioned running shoes for maximum comfort', 11, 3),
  ('ASICS GEL-Contend 7', 'https://example.com/asics_gel_contend_7.jpg', 'Affordable ASICS running shoes for beginners', 10, 11),
  ('Nike Free RN 5.0', 'https://example.com/nike_free_rn_5.jpg', 'Flexible and lightweight Nike running shoes', 9, 17),
  ('Adidas Terrex Swift R3 GTX', 'https://example.com/adidas_terrex_swift_r3.jpg', 'Durable and waterproof Adidas hiking shoes', 13, 8),
  ('Puma Clyde Court', 'https://example.com/puma_clyde_court.jpg', 'Performance basketball shoes with Puma style', 12, 19),
  ('New Balance 1500', 'https://example.com/nb_1500.jpg', 'Sleek New Balance sneakers with a modern design', 8, 14),
  ('Reebok Nano X1', 'https://example.com/reebok_nano_x1.jpg', 'Versatile training shoes for high-intensity workouts', 11, 6),
  ('Under Armour Charged Bandit 6', 'https://example.com/ua_charged_bandit_6.jpg', 'UA running shoes with Charged Cushioning', 10, 3),
  ('Brooks Levitate 4', 'https://example.com/brooks_levitate_4.jpg', 'Energetic Brooks running shoes with responsive cushioning', 11, 15),
  ('Converse Run Star Hike', 'https://example.com/converse_run_star_hike.jpg', 'Elevated platform Converse sneakers for a bold look', 7, 22),
  ('Salomon X Ultra 3', 'https://example.com/salomon_x_ultra_3.jpg', 'Sturdy Salomon hiking shoes for technical terrain', 14, 10),
  ('Nike Air Force 1', 'https://example.com/nike_air_force_1.jpg', 'Timeless Nike sneakers with classic style', 9, 5),
  ('Adidas Pureboost', 'https://example.com/adidas_pureboost.jpg', 'Adidas running shoes with a responsive boost midsole', 10, 12),
  ('Puma Calibrate Runner', 'https://example.com/puma_calibrate_runner.jpg', 'Innovative Puma running shoes with XETIC technology', 11, 8),
  ('New Balance Fresh Foam Roav', 'https://example.com/nb_fresh_foam_roav.jpg', 'Casual New Balance sneakers with a modern design', 8, 15),
  ('Saucony Endorphin Speed', 'https://example.com/saucony_endorphin_speed.jpg', 'Fast and responsive Saucony running shoes', 11, 18),
  ('Reebok ZigWild Trail 6', 'https://example.com/reebok_zigwild_trail_6.jpg', 'Trail running shoes with Reeboks ZigTech cushioning', 10, 6),
  ('Under Armour Tribase Reign 3', 'https://example.com/ua_tribase_reign_3.jpg', 'UA training shoes designed for stability and versatility', 9, 14),
  ('Brooks Addiction Walker', 'https://example.com/brooks_addiction_walker.jpg', 'Comfortable Brooks walking shoes with support', 12, 10),
  ('Converse Jack Purcell', 'https://example.com/converse_jack_purcell.jpg', 'Classic Converse sneakers with a timeless design', 7, 22),
  ('Salomon Sense Ride 4', 'https://example.com/salomon_sense_ride_4.jpg', 'Versatile Salomon trail running shoes with comfort features', 14, 3),
 ('Nike Joyride Run Flyknit', 'https://example.com/nike_joyride_run_flyknit.jpg', 'Innovative Nike running shoes with Joyride cushioning', 9, 16),
  ('Adidas Nite Jogger', 'https://example.com/adidas_nite_jogger.jpg', 'Reflective Adidas sneakers for nighttime running', 8, 12),
  ('Puma RS-Fast', 'https://example.com/puma_rs_fast.jpg', 'Puma lifestyle sneakers with a futuristic design', 10, 5),
  ('New Balance FuelCell Propel', 'https://example.com/nb_fuelcell_propel.jpg', 'New Balance running shoes with FuelCell technology', 11, 18),
  ('Saucony Shadow 6000', 'https://example.com/saucony_shadow_6000.jpg', 'Classic Saucony sneakers with retro vibes', 8, 20),
  ('Reebok Classic Nylon', 'https://example.com/reebok_classic_nylon.jpg', 'Timeless Reebok sneakers with a nylon upper', 7, 15),
  ('Under Armour HOVR Guardian 2', 'https://example.com/ua_hovr_guardian_2.jpg', 'Stability running shoes with UA HOVR technology', 10, 7),
  ('Brooks Revel 4', 'https://example.com/brooks_revel_4.jpg', 'Versatile Brooks running shoes for everyday use', 9, 11),
  ('Converse Chuck 70 Low', 'https://example.com/chuck_70_low.jpg', 'Low-top version of the classic Chuck 70 sneakers', 7, 3),
  ('Salomon XA Elevate', 'https://example.com/salomon_xa_elevate.jpg', 'Durable Salomon trail running shoes with extra support', 12, 14),
  ('Nike Renew Run', 'https://example.com/nike_renew_run.jpg', 'Nike running shoes with plush cushioning for a smooth ride', 9, 16),
  ('Adidas Stan Smith Primegreen', 'https://example.com/adidas_stan_smith_primegreen.jpg', 'Sustainable version of the iconic Adidas Stan Smith', 8, 12),
  ('Puma Future Rider Play On', 'https://example.com/puma_future_rider_play_on.jpg', 'Vibrant and playful Puma sneakers with retro flair', 10, 5),
  ('New Balance 327', 'https://example.com/nb_327.jpg', 'Casual lifestyle sneakers with a heritage-inspired design', 11, 18),
  ('Saucony Kinvara 12', 'https://example.com/saucony_kinvara_12.jpg', 'Lightweight and responsive Saucony running shoes', 8, 20),
  ('Reebok Classic Leather Legacy', 'https://example.com/reebok_classic_leather_legacy.jpg', 'Modern take on the classic Reebok leather sneakers', 7, 15),
  ('Under Armour HOVR Sonic 4', 'https://example.com/ua_hovr_sonic_4.jpg', 'Connected running shoes with UA HOVR technology', 10, 7),
  ('Brooks Ghost 14', 'https://example.com/brooks_ghost_14.jpg', 'Neutral running shoes with plush cushioning for comfort', 9, 11),
  ('Converse Chuck Taylor All Star II', 'https://example.com/chuck_taylor_all_star_ii.jpg', 'Updated version of the classic Chuck Taylor with modern features', 7, 3),
  ('Salomon XA Pro 3D V8', 'https://example.com/salomon_xa_pro_3d_v8.jpg', 'Durable trail running shoes with enhanced stability', 12, 14),
  ('Nike Air Zoom Pegasus 38', 'https://example.com/nike_air_zoom_pegasus_38.jpg', 'Versatile Nike running shoes with Zoom Air cushioning', 9, 16),
  ('Adidas Ultraboost 21', 'https://example.com/adidas_ultraboost_21.jpg', 'High-performance Adidas running shoes with Boost technology', 8, 12),
   ('Puma RS-X3 Puzzle', 'https://example.com/puma_rs_x3_puzzle.jpg', 'Puma sneakers with a unique puzzle-inspired design', 10, 5);
 
 
  
