CREATE TABLE Shoes (
  ID INTEGER  NOT NULL AUTO_INCREMENT,
  Sname VARCHAR(30) NULL,
  image INTEGER  NULL,
  details TEXT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE Specific_Shoe (
  Spec_ID INTEGER  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Shoes_ID INTEGER  NOT NULL,
  Price VARCHAR(30) NULL,
  order_type VARCHAR(30) NULL,
  stock INT NULL,
  Sort INTEGER  NULL,
  date_added TIMESTAMP NULL,
 FOREIGN KEY (Shoes_ID) REFERENCES Shoes(ID) 
);


CREATE TABLE Category_Shoe (
  CS_ID INTEGER  NOT NULL AUTO_INCREMENT,
  shoe_id INTEGER  NULL,
  Cat_id INTEGER  NULL,
  PRIMARY KEY(CS_ID),
  FOREIGN KEY (shoe_id) REFERENCES Shoes(ID), 
  FOREIGN KEY (cat_id) REFERENCES Category(Cat_ID)
);


CREATE TABLE Category (
  Cat_ID INTEGER NOT NULL AUTO_INCREMENT,
  Cname VARCHAR(30) NULL,
  created_at TIMESTAMP NULL,
  PRIMARY KEY(Cat_ID)
);


CREATE TABLE Shoe_Color (
  SC_Id INTEGER  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Shoe_ID INTEGER  NOT NULL,
  Color_ID INTEGER  NOT NULL,
  FOREIGN KEY (Shoe_ID) REFERENCES Shoes(ID), 
  FOREIGN KEY (Color_ID) REFERENCES Color(Color_ID)
);

CREATE TABLE Color (
  Color_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Color_name VARCHAR(40) NULL,
  created_Id TIMESTAMP NULL,
  updated_Id TIMESTAMP NULL
  
);

CREATE TABLE Shoe_Image (
  Img_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Shoes_ID INTEGER NOT NULL,
  img_url TEXT NULL,
  FOREIGN KEY (Shoes_ID) REFERENCES specific_shoe(Spec_ID) 
);

CREATE TABLE Sizes (
  Size_ID INTEGER  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SNumber VARCHAR(10) NULL,
  details TEXT NULL,
  created_date TIMESTAMP NULL,
  updated_date TIMESTAMP NULL
);

CREATE TABLE Shoe_Size (
  SS_ID INTEGER  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Shoes_ID INTEGER  NOT NULL,
  Size_ID INTEGER  NOT NULL,
  FOREIGN KEY(Shoes_ID) REFERENCES specific_shoe(Spec_ID),
  FOREIGN KEY(SIze_ID) REFERENCES Sizes(Size_ID)
 );



ALTER TABLE Shoe_Size ENGINE=INNODB;
ALTER TABLE Sizes ENGINE=INNODB;
ALTER TABLE Specific_Shoe ENGINE=InnoDB;
ALTER TABLE Shoe_Color ENGINE=InnoDB;
ALTER TABLE Color ENGINE=InnoDB;
ALTER TABLE Shoes ENGINE=InnoDB;
ALTER TABLE Category_Shoe ENGINE=InnoDB;
ALTER TABLE Category ENGINE=InnoDB;
ALTER TABLE Shoe_Image ENGINE=InnoDB;
